"""Add password fields

Revision ID: 522ef57098ad
Revises: 56d7171895ab
Create Date: 2022-11-20 13:57:46.528415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522ef57098ad'
down_revision = '56d7171895ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashedPassword', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashedPassword')
    # ### end Alembic commands ###
