"""Change id to uuid

Revision ID: a887d30d48ba
Revises: bdcba65f3c5a
Create Date: 2022-11-20 16:41:45.068562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a887d30d48ba'
down_revision = 'bdcba65f3c5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
